### ISSUE TITLE
Missing FullScreenPassRenderer Feature

### ISSUE THREAD

**Issue by strudgian** [cnkblgn/Unity-Asset-URP-Fullscreen-Overlay-Shader#1]
The image below shows a missing render feature, can you advise on how I can either recreate or find it. Alternatively could you update the repo with this?

![devenv_qXCM1LXPrU](https://github.com/cnkblgn/Unity-URP-Sample-Scope-Shader/assets/8452312/a55312d4-71ad-4d3e-ad5b-a4d21924afca)

**Comment by cnkblgn** [comment]
Are you using Universal Render Pipeline 14.0.9 or newer? It works fine on my end. This references FullScreenPassRendererFeature asset for enabling and disabling.

![Screenshot (65)](https://github.com/cnkblgn/Unity-URP-Sample-Scope-Shader/assets/91436084/8e5903c0-591c-475d-9e94-5a0b325bee10)

**Comment by strudgian** [comment]
Hey! Thanks for responding. Yeah that's why I closed the issue as I derped out and tried to open this in a lower version of 2022.3. I have the fullscreenpassrendererfeature. However the textures apparently cannot be read. Any tips?

**Comment by cnkblgn** [comment]
Maybe the unity package or texture is corrupted. I don't know why. But you can use any texture you want. 1:1 ratio (512x512). Also, you can use this for other overlays like gas masks, blood splatters, etc.

**Comment by strudgian** [comment]
Working for me now thank you for the guidance! :) Have you ever had thoughts about implementing this in VR? I'm currently working on potentially making this work for either the left or right eye for an oculus quest 2

**Comment by cnkblgn** [comment]
Unfortunately :(, I do not have any VR experience. This shader uses the current screen texture (URP Sample Buffer) and manipulates its UV coordinates. Maybe you can grab left or right eye screen texture from Unity, after that, you can use its UV coordinates for the shader.
